### ISSUE TITLE
Main SSE vocabularies not being displayed in dialog or drop down

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/coopsuk#14] opened 2022-12-05 10:48 UTC
**Describe the bug**
There are no Activities, Typology or Struture type getting through in the data

Typology: undefined
Structure Type: undefined
Main Activity: undefined

**To Reproduce**
Go to https://coopsuk.solidarityeconomy.coop
Search for anything

**Expected behavior**
There should be choices for all those fields

**Screenshots**
![image](https://user-images.githubusercontent.com/108667445/205618481-849ac364-487c-4e24-a51f-35f031e8abf5.png)

**Comment by wu-lee** [comment] 2022-12-05 12:32
The drop downs seem to "work" in that they filter stuff down, and there are >0 things to select, but they're all blank.

On further inspecton, the vocab fields in the data have full URIs, whereas the vocab indexes have shortened ones, so they don't match.  So for example, `https://dev.lod.coop/essglobal/2.1/standard/organisational-structure/OS130` does not match `os:OS130`.  I'm not sure why there is the discrepancy, as this has been working before, but will investigate.

**Comment by wu-lee** [comment] 2022-12-05 12:57
So the problem is a mix-up between dev and prod data / vocab.  Because the vocab URIs are used to shorten the data URIs, if they don't match they don't get shortened, which results in the vocab look-ups failing.

The fix is to not mix them up!  I've redeployed the production version, and it seems to have done the job, will do the dev version next.

**Comment by wu-lee** [comment] 2022-12-05 14:19
Dev redeployed, so I think this is now fixed.  Changes committed to dev/master branches of this project.

**Comment by ColmDC** [comment] 2022-12-05 15:34
How long would that have been there?

**Comment by wu-lee** [comment] 2022-12-06 15:57
Probably since the last time I deployed, order of a few days?

**Comment by wu-lee** [comment] 2022-12-06 16:33
Possibly we should have a more obvious (read: severe) failure mode for this.

**Closed** 2022-12-06 21:46 UTC
Labels: bug
